import glob
import pandas as pd
from snakemake.utils import validate
from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("6.4.1")


##### setup report #####
configfile: "config/config.yaml"


# report: "report/workflow.rst" ## Why this?


##### load rules #####


include: "rules/common.smk"
include: "rules/window.smk"
include: "rules/analyze.smk"

##### target rules #####

rule all:
    input:
#        "results/scaffold1_12.raxml.bestTree"
#        get_R_outs(),
        "results/metrics.tsv"
